import { v4 as uuidv4 } from 'uuid';
import { FoodItem } from '@/types';

export const placeholderFoods: FoodItem[] = [
  {
    id: uuidv4(),
    food_name: 'Margherita Pizza',
    food_rating: 4.5,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Italian Bistro',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 12.99,
  },
  {
    id: uuidv4(),
    food_name: 'Chicken Burger',
    food_rating: 4.0,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Burger Bonanza',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 8.99,
  },
  {
    id: uuidv4(),
    food_name: 'Sushi Platter',
    food_rating: 4.8,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Sushi Haven',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Closed',
    price: 20.99,
  },
  {
    id: uuidv4(),
    food_name: 'Pasta Carbonara',
    food_rating: 4.2,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Pasta Palace',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 14.49,
  },
  {
    id: uuidv4(),
    food_name: 'Tacos Al Pastor',
    food_rating: 4.6,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Taco Truck',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 9.99,
  },
  {
    id: uuidv4(),
    food_name: 'Fried Rice',
    food_rating: 4.1,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Wok Star',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Closed',
    price: 10.49,
  },
  {
    id: uuidv4(),
    food_name: 'Caesar Salad',
    food_rating: 4.3,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Green Eats',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 7.99,
  },
  {
    id: uuidv4(),
    food_name: 'BBQ Ribs',
    food_rating: 4.7,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Smokehouse Grill',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 18.99,
  },
  {
    id: uuidv4(),
    food_name: 'Pad Thai',
    food_rating: 4.4,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Thai Spice',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Closed',
    price: 13.49,
  },
  {
    id: uuidv4(),
    food_name: 'Chocolate Cake',
    food_rating: 4.9,
    food_image: 'https://via.placeholder.com/300',
    restaurant_name: 'Sweet Treats',
    restaurant_logo: 'https://via.placeholder.com/50',
    restaurant_status: 'Open Now',
    price: 6.99,
  },
];